volumes:
  locker: {}

services:
  locker-backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8443:8443"
    env_file:
      - .env
    volumes:
      - ./ssl_certificates:/ssl_certificates:ro
  locker-db:
    image: postgres:latest
    ports:
      - ":5432"
    volumes:
      - locker:/var/lib/postgres/data
      - ./src/database/migrations/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_URL=${DATABASE_HOST}
      - POSTGRES_DB=${DATABASE_SCHEMA}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}